### ISSUE TITLE
WP_HOME not imported from .env & "autodetection" fails

### ISSUE THREAD

**Issue by kai-jacobsen** [wecodemore/wpstarter#10]
1. WP_HOME, if manually set, is not imported. 
Seems to be fixed when added to the static $isString array in Env.php

2. If WP_HOME is not set (which currently is the default case), the script in wp-config around LINE 116 may fail under certain conditions when php runs as cgi. 
See: http://stackoverflow.com/questions/21889304/do-not-access-superglobal-server-array-directly-on-netbeans-7-4-for-php 
which links to 
http://php.net/manual/en/function.filter-input.php#77307

so fixing 1. would at least help to avoid 2.

**Comment by Giuseppe-Mazzapica** [comment]
This is a bug. Auto setting of WP_HOME is last resort, there is the **need** to set it. Thanks for your reporting.
