### ISSUE TITLE
Default installation seems to have trouble working with `php -S`

### ISSUE THREAD

**Issue by quinn** [wecodemore/wpstarter#102]
I am using the default installation, and am experiencing some issues. First, i had to add:

```
remove_filter('template_redirect','redirect_canonical');
```
to:
```
/wp/wp-content/themes/twentynineteen/functions.php
```

Without that, when i would go to, e.g. `localhost:4000`, it would redirect to remove the port. With that disabled, it would stop the redirect, but some of the theme assets return a 404 because they, have an extra prefix, e.g: 

```
<link rel='stylesheet' id='twentynineteen-style-css'  href='/wp/wp/wp-content/themes/twentynineteen/style.css?ver=1.4' type='text/css' media='all' />
```

Are these common issues / how can I fix? I've tried a lot of fixes from google having to do with HOME and SITEURL, but nothing has seemed to help.

**Comment by lkraav** [comment]
@quinn what is your `WP_HOME` setting value?

You might be dealing with the same thing as https://github.com/wecodemore/wpstarter/issues/101

**Comment by gmazzap** [comment]
Please check if 4c76d9d solved it. Thanks.
