### ISSUE TITLE
ENV File Behavior and Manipulation #Question

### ISSUE THREAD

**Issue by MugShotGG** [wecodemore/wpstarter#104]
was looking at trying to use this as part of a build/release pipeline to start slimming down the repo sizes for our wordpress sites as they are currently wholesale checked into the repo and wp-configs are copied in via release steps. I was hoping this might slide right in to current process. 

Is there any way that i can build the WP install once and drop in a dev.env qa.env stage.env prod.env when we get to deploying the package? I'm trying to prevent building 4 copies of the same site or the artifact and space creep on this would get out of hand and composer installing on a prod server seems non optimal(though i could be very wrong im just concerned about the affect it would have on a prod box)

**Comment by gmazzap** [comment]
I don't understand what you are asking :)

Can you please expand a bit on what are you requirements?

Normally different environments means different servers, so iI don't understand how you could have different servers using the same WP installation.

Regarding environment, you can have different environment files for the same WP installation, but environment files can only contain configuration values, not code.
So if you have a plugin in X version to be used in production and X-dev to be used in development, having a different environemnt configuration can't do that.

Finally, there's nothing wrong in running Composer in production environment, assuming the "build" process does not affect the webserver processing incoming requests.

**Comment by MugShotGG** [comment]
I think i got what i needed from your last reply 😅  Sorry for my wording 

The only difference in our .env files would be DB information so i was hoping to 'Composer install' once on my build server and then deploy the same Wordpress instance to TEST/QA/Prod but ONLY update the .env file in each server.

It seams that the .env file is only read at build time which answers the main question i had. Thank you very much!

**Comment by gmazzap** [comment]
@MugShotGG you can do better :)

Environment variables can be written in the environment, i.e. at webserver ([Apache](https://httpd.apache.org/docs/2.4/env.html#:~:text=The%20most%20basic%20way%20to,server%20using%20the%20PassEnv%20directive.) / [Nginx](http://nginx.org/en/docs/ngx_core_module.html#env)) level.

That means that you could have an `.env` file with _shared_ configuration you could deploy in all the environments, and for environment-specific configuration use the _real_ environment.

This way you don't even need to worry about having different env files. Yes, that also means that to change an env variable it is required to access the server configuration, but first of all I think that's something that doesn't happen frequently and besides that it is also a good idea security wise.

**Comment by MugShotGG** [comment]
Thats fantastic to hear. I'll have to check that out. Thank you!
