### ISSUE TITLE
ETA for `v3` release with Composer 2 support?

### ISSUE THREAD

**Issue by tyrann0us** [wecodemore/wpstarter#106]
Hi @gmazzap and @franz-josef-kaiser!

We are in the process of (finally) upgrading Composer to `v2` and noticed that WP Starter supports it, but not in a tagged (pre-release) version. You added support for Composer `v2` in November 2020 (https://github.com/wecodemore/wpstarter/commit/d871a8a1d33cf6c954a5906780d3b415682c63a5#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R39), but the latest tag is from September 2020 (https://github.com/wecodemore/wpstarter/releases/tag/3.0.0-beta.6).

Are you planning a pre-release or maybe even a stable `v3` that includes Composer `v2` support? I am not a big fan of having `dev-master` version restrictions in production.

BTW, we have been using the `v3` betas for many months with no problems, is there anything preventing a final `v3` release?

Thanks a lot!

**Comment by gmazzap** [comment]
We could tag a pre-release.

Regarding a stable release, I don't have knowledge of enough test cases to consider is "stable", and there's no autmatism to check for PHP 8.0+... Both things I would like to have before releaseing v3 stable.

**Comment by gmazzap** [comment]
Released [3.0.0-beta.7](https://github.com/wecodemore/wpstarter/releases/tag/3.0.0-beta.7)
