### ISSUE TITLE
Allow composer installers v2

### ISSUE THREAD

**Issue by luislard** [wecodemore/wpstarter#109]
**Is your feature request related to a problem? Please describe.**
composer/installers dependency is outdated current constraint is: ^1.6 

composer installers current version is ^2 (has been releases 4 months ago) [see here](https://github.com/composer/installers/blame/v2.0.0/CHANGELOG.md#L11)

Looking at the changelog it seems that there is no change it could break this package. 

**Describe the solution you'd like**

change restriction from ^1.6 to ^2.0

**Comment by gmazzap** [comment]
Composer installers v2 requires PHP 7.2, so I would need to bump the min PHP version.

I guess we can require `^1.9 || ^2` which would allow it, but not force.

**Comment by gmazzap** [comment]
composer/installers v2 is now allowed. https://github.com/wecodemore/wpstarter/blob/dev/composer.json#L40

I allow both ^1.9 and ^2, so packages which use ^1 are not blocked by WP Starter, but at project level it will be possible to decide  for oe or the other.

**Comment by luislard** [comment]
this is better :+1:
