### ISSUE TITLE
Can't contribute due to dependencies

### ISSUE THREAD

**Issue by luislard** [wecodemore/wpstarter#110]
**Describe the bug**

![image](https://user-images.githubusercontent.com/17932063/143321231-45143e22-5f23-40f5-b022-79203a078b5e.png)

**To Reproduce**
1. Clone the repo
2. git checkout dev
3. run composer install (use composer v2)

**Expected behavior**
Not having this error

**System (please complete the following information):**
 - OS: Linux
 - Version `5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Additional context**

**Comment by luislard** [comment]
The package is required by wp-cli as dev-master too, 
Option 1:
we remove it, install it again using the "*" and then commit the composer.lock file to avoid having the issue.

What do you think?

**Comment by gmazzap** [comment]
I'm already working at a fic. Bumping WP CLI to 2.5 solves the issues already.

**Comment by gmazzap** [comment]
Fixed in [3.0.0-beta.8](https://github.com/wecodemore/wpstarter/releases/tag/3.0.0-beta.8) whic is in sync with `dev` branch right now.

**Comment by luislard** [comment]
@gmazzap thanks!
