### ISSUE TITLE
Documentation: how to publish wpstarter branch-based app builds, similar to Netlify etc JS apps

### ISSUE THREAD

**Issue by lkraav** [wecodemore/wpstarter#116]
## Is your feature request related to a problem? 
Dev team looks to publish wpstarter-based app branch changes for pre-merge QA for various other teams, product team for one.

## Describe the solution you'd like
After a wpstarter branch is pushed to GH, an action builds it, publishes an access URL at the bottom of PR screen, similar to Netlify etc

##  Describe alternatives you've considered
Tunneling localhost builds, but almost all of the experience is worse with it.

## Additional context
Maybe later, after some discussion whether this is even possible to achieve with a non-static app like WP?

**Comment by gmazzap** [comment]
Not sure this is something that has anything to do with WP Starter.

These days there are many ways to build app stacks "on demand" for testing. One of the simplest way is probably Heroku Flow. 

The thing is that modern PHP apps have a composer.json file and _everything_ is needed to spin-up the code is a `composer install`.

WP Starter brings that into the WordPress world, so you can use any of the "cloud native" opportunities that are available for PHP application builts with frameworks like Laravel or Symfony.

**Comment by lkraav** [comment]
Thanks.

There are some WP specifics to be figured out, like db state perhaps etc, so I think it's a useful discussion in WPS context. 

We'll give some things a try and document the results here.

**Comment by gmazzap** [comment]
I'm cleaning things up.

While there might be things to say, the project documentation in this repo does not feel like a good place.

One could be articles and even a book about "Modern WP development with WP Starter".

But the official documentation is not a good place for this, it is already big and scary as it is.
