### ISSUE TITLE
Strict standards note for Dotenv::load()

### ISSUE THREAD

**Issue by franz-josef-kaiser** [wecodemore/wpstarter#12]
Currently there's the [`WCM\WPStarter\Env::load( $path );` method](https://github.com/wecodemore/wpstarter/blob/d89f91d66917c8517c9fa684d7c418480a7301ab/wpstarter/src/Env.php#L171) where the class itself extends the `Dotenv` class. Trying to import the WPTest XML, I get the following error

```bash
$ wp import wptest.xml --authors=create --path=/var/www/dev/public/wp
PHP Strict standards:  Declaration of WCM\WPStarter\Env::load() should be compatible with Dotenv::load($path, $file = '.env') in /var/www/dev/vendor/wecodemore/wpstarter/wpstarter/src/Env.php on line 23
```

We should use `$file = ''` as second argument.

**Comment by franz-josef-kaiser** [comment]
Switched to `null` as default as that _should_ be good enough.

**Comment by franz-josef-kaiser** [comment]
Tested and works (even if the second `$path` is quite unnecessary at the moment). Done with 28e51b2

**Comment by Giuseppe-Mazzapica** [comment]
@franz-josef-kaiser `Dotenv` released [version  2](https://github.com/vlucas/phpdotenv/releases/tag/v2.0.1) that changed the way it works (for the better). We should upgrade to that version.

I'm going to re-open this issue as a reminder, but changing Milestone to `2.2`.

**Comment by GaryJones** [comment]
Probably related here, but I see that Dotenv supports passing in a file name.

My situation is that I've got a `/var/www` that contains directories for different sites. If I want to store multiple .env files, one for each site, above the public roots, I'll obviously need different filenames. Being able to pass through the file name as the second arg in the `$env = WCM\WPStarter\Helpers::settings(__DIR__);` call would be handy.

**Comment by franz-josef-kaiser** [comment]
@GaryJones Could you please directly link to files so reading things up is easier?

*ProTip:* You can click line numbers to append them to the Url (hold _Shift_ for multiple lines). Also press the _Y_ key to get a link to a specific commit blob, so the link is not a moving target with future versions released. Thanks!

**Comment by Giuseppe-Mazzapica** [comment]
@GaryJones When I'll refactor to use Dotenv v2, I'll add possibility to customize file name. That should happen first weekend after my vacation, that is 1st weekend of september. Thanks for reporting.

**Comment by franz-josef-kaiser** [comment]
@Giuseppe-Mazzapica I add a ticket for upgrading to v2 of PHPDotenv
