### ISSUE TITLE
3.0.0-beta.9: with `.env` cache loaded, site is always Environment Type "production"

### ISSUE THREAD

**Issue by lkraav** [wecodemore/wpstarter#122]
## Describe the bug
Calculated `WP_ENVIRONMENT_TYPE` does not seem to get persisted in `.env.cached.php`.

## To Reproduce
1. In `.env` set `WP_ENV=development`
2. Delete `.env.cached.php`
3. Load site, preferrably with Query Monitor plugin installed.
4. See Query Monitor > Environment panel: says "WordPress > Environment Type: development"
5. Verify `.env.cached.php` was created.
6. Reload site.
7. See Query Monitor > Environment panel: says "WordPress > Environment Type: production"

## Expected behavior
`WP_ENVIRONMENT_TYPE` remains matching original `WP_ENV` value.

## System (please complete the following information):
 - OS: Linux

## Additional context
N/A

**Comment by lkraav** [comment]
> But it should reflect what the .env file (or real environment variable) has for WP_ENV.

It does. But this value is not translated into WP_ENVIRONMENT_TYPE later.

Uncached vs cached result difference I think shows there's definitely *some* kind of a bug here.

**Comment by gmazzap** [comment]
Ok, looking at the code I think I spotted the issue.

When the env is _not_ cached, wp-config defines the constants, and it is there that `WP_ENVIRONMENT_TYPE` is mapped from `WP_ENV`.

When the env is cached, there's wp-config does _not_ defines constants, because it relies on the cache file to define the constants.

But because `WP_ENVIRONMENT_TYPE` is not cached, it never gets defined in this scenario, and so WordPress fallbacks to production.

**Comment by gmazzap** [comment]
@lkraav would you be able to test the code in the [`bugfix/122-wp-env-type-not-mapped`](https://github.com/wecodemore/wpstarter/tree/bugfix/122-wp-env-type-not-mapped) branch?

**Comment by lkraav** [comment]
> [`bugfix/122-wp-env-type-not-mapped`](https://github.com/wecodemore/wpstarter/tree/bugfix/122-wp-env-type-not-mapped)

WP_ENV value was correctly reflected.

But after I removed `.env.cached.php` to test a fresh cache, I get "Error establishing a database connection" - it seems like not all constants are making it into the cache now?

**Comment by lkraav** [comment]
> But after I removed `.env.cached.php` to test a fresh cache, I get "Error establishing a database connection" - it seems like not all constants are making it into the cache now?

Pffft, nevermind! User error, of course. i had a test value of `staging`, and no corresponding `.env.staging` file with overrides.

Changing `WP_ENV` values now seems to work as expected :tada: Tyvm for this fast response.

**Comment by gmazzap** [comment]
Released in [3.0.0-beta.10](https://github.com/wecodemore/wpstarter/releases/tag/3.0.0-beta.10)
