### ISSUE TITLE
Allow changing the .env file

### ISSUE THREAD

**Issue by franz-josef-kaiser** [wecodemore/wpstarter#13]
As requested by @GaryJones in #12 [here](https://github.com/wecodemore/wpstarter/issues/12#issuecomment-134510143):

> Probably related here, but I see that Dotenv supports passing in a file name.

> My situation is that I've got a `/var/www` that contains directories for different sites. If I want to store multiple `.env` files, one for each site, above the public roots, I'll obviously need different filenames. Being able to pass through the file name as the second arg in the [`$env = WCM\WPStarter\Helpers::settings(__DIR__);`](https://github.com/wecodemore/wpstarter/blob/b1ff2f10781a1c918995f287a0a8d138323bf063/wpstarter/templates/wp-config.example#L28) call would be handy.

**Comment by Giuseppe-Mazzapica** [comment]
Done.
