### ISSUE TITLE
Remove deprecated FORCE_SSL_LOGIN

### ISSUE THREAD

**Issue by GaryJones** [wecodemore/wpstarter#20]
`FORCE_SSL_LOGIN` was deprecated in WP 4.0 in favour of `FORCE_SSL_ADMIN`. WPStarter contains both fields. Either the old one should be removed (new installs shouldn't even consider using it), or a note added to indicate that `FORCE_SSL_ADMIN` is the correct version to use.

**Comment by Giuseppe-Mazzapica** [comment]
Thanks @GaryJones done with 2f5e21c in dev branch, will be merged soon.
