### ISSUE TITLE
Reduce distribution package size

### ISSUE THREAD

**Issue by franz-josef-kaiser** [wecodemore/wpstarter#26]
Currently we distribute _a lot_ with the whole package. The export actually also contains `/docs` if I am not mistaken. Composer [per default uses `--prefer-dist`](https://getcomposer.org/doc/03-cli.md#install) (unless told to fetch from source) and therefore uses git archives. Now the size of an archive can be reduced by introducing a `.gitattributes` file and [ignoring specific non-distribution files](https://git-scm.com/docs/gitattributes#_creating_an_archive).

**Edit:** As I was just looking around, I found [this mess](https://github.com/sensiolabs/SensioDistributionBundle/blob/3a160355bb1364da55ed9e415c1aa1fa8d457b6f/Resources/bin/build.sh#L61-L140) in a GitHub repo. We can avoid that.

**Comment by Giuseppe-Mazzapica** [comment]
I'm going to merge the branch into `dev` so it will be part of next release.

**Comment by Giuseppe-Mazzapica** [comment]
@franz-josef-kaiser it's merged on dev. We can close this, right?

**Comment by franz-josef-kaiser** [comment]
Done with 0abea7a
