### ISSUE TITLE
Add platform requirements

### ISSUE THREAD

**Issue by franz-josef-kaiser** [wecodemore/wpstarter#27]
There's the option to set [platform requirements](https://getcomposer.org/doc/02-libraries.md) for Composer. As those are _skippable_, they do no harm, but might show a user how to set up an OS that is capable of delivering the full feature set that WordPress has under its hood. 
### Analysis of the packages that WP is able to use in core:

``` sh
        Extension  Matches REF        EXT min/Max PHP min/Max     PHP all
        -----------------------------------------------------------------
        Core               Core                   4.0.0           5.3.0      
*       PDO                PDO        5.1.0       5.1.0                      
        Reflection         Reflection 5.0.0       5.0.0                      
        SimpleXML          SimpleXML  5.0.0       5.0.0           5.0.1      
     C  com_dotnet         user                   4.0.0                      
*       ctype              ctype      4.0.4       4.0.4                      
*       curl               curl       4.0.2       4.0.2           4.0.4      
        date               date       4.0.0       4.0.0           5.2.0      
*       dom                dom        5.0.0       5.0.0                      
°      ereg               ereg       4.0.0       4.0.0                      
*       exif               exif       4.2.0       4.2.0                      
~       fileinfo           fileinfo   1.0.5-dev   5.3.0                      
        filter             filter     0.9.4       4.0.0           5.0.0      
~    C  ftp                ftp        4.0.0       4.0.0           5.0.0      
*    C  gd                 gd         4.0.0       4.0.0           4.3.2      
*       gettext            gettext    4.0.0       4.0.0                      
        hash               hash       1.1         4.0.0           5.6.0beta1 
*       iconv              iconv      4.0.5       4.0.5           5.0.0      
*    C  imagick            user                   4.0.0           5.1.3      
*       intl               intl       2.0.0b1     5.2.4           5.4.0RC3   
*       json               json       5.3.0       5.3.0           5.5.0      
     C  libsodium          user                   4.0.0                      
*       libxml             libxml     5.2.11      5.2.11                     
        mbstring           mbstring   4.0.6       4.0.6           5.0.0      
*    C  mcrypt             user                   4.0.0                      
*       memcache           memcache   0.2         4.3.3                      
*    C  mysql              user                   4.0.0           5.2.3      
*    C  mysqli             user                   4.0.0           5.0.0      
*    C  openssl            user                   4.0.0           5.3.0      
     C  pcre               pcre       4.0.0       4.0.0           5.2.4      
*       posix              posix      4.0.0       4.0.0                      
*    C  sockets            user                   4.0.0           4.3.0      
        spl                spl        5.1.2       5.1.2           5.2.0      
*    C  ssh2               user                   4.0.0                      
        standard           standard   4.0.0       4.0.0 => 5.6.16 5.4.0      
        tokenizer          tokenizer  4.2.0       4.2.0                      
     C  xdiff              user                   4.0.0                      
*    C  xml                xml        4.0.0       4.0.0           4.0.5      
*    C  xmlreader          user                   4.0.0           5.0.0      
*       zip                zip        1.6.0       5.2.0                      
*    C  zlib               zlib       4.0.4       4.0.4           5.4.0
        -----------------------------------------------------------------
        Total [41]                                5.3.0 => 5.6.16 5.6.0beta1
```

During the Slack discussion with @Giuseppe-Mazzapica we found the following things that are worth documenting:
- Some libraries might be mandatory like `gettext` and `intl` for translations and locale information
- While some packages are bundled with PHP core, they might be needed to be set [for running the `configure` process](http://php.net/manual/en/configure.php) like enabling older MySQL drivers (PHP 5.4+ comes with `mysqlnd` while WP uses `mysql`, `mysqli`) or `--enable-mbstring`.
### Examples
- `ext-gd`, `ext-libjpeg-turbo`, …
- `lib-curl`, `lib-iconv`, …

**Comment by Giuseppe-Mazzapica** [comment]
We are already requireing PHP 5.3+ which means that most of the things WP needs (and that are listed in the table in OP) are always there.

Moreover I don't want to add _requirements_ for things that are not real requirements.

AD mysqli is always included in PHP 5.3+.

`gettext` and `intl` are bundled with PHP 5.3+, but needs special flag when building PHP from sources, so makes sense add them as dependencies. 

Regarding `GD` and `ImageMagick`, the former is bundled (but needs flags on compile) while `ImageMagick` needs to be installed separately.

WordPress can work with the one or the other, but Composer does not provide the possibility to require one _or_ the other. We could maybe add suggestion for `ImageMagick`.

This is what I propose:

### Requirements

- `ext-gettext`
- `ext-intl`

### Suggestions

- `ext-imagick`

**Comment by franz-josef-kaiser** [comment]
@Giuseppe-Mazzapica I'll take a look at the PHP `configure` flags list and try to go through the requirements one by one. Else the _requirements_ and _suggestions_ LGTM.

**Comment by Giuseppe-Mazzapica** [comment]
Probably `ext-curl` should go on suggestions as well

**Comment by franz-josef-kaiser** [comment]
Same goes for `ext-gd` _or_ `ext-imagick` – you know the conflict I am talking about now…

**Comment by schlessera** [comment]
> WordPress can work with the one or the other, but Composer does not provide the possibility to require one or the other.
Yes it does, through virtual packages. However, the actual packages that are pulled in need to support it.
So, you require a virtual package like so:
 ```
require: {
    "wordpress/image-manipulation-library": "*"
}
```
Then you can have both `gd` & `imagick` do this:
```
provide: {
   "wordpress/image-manipulation-library": "1.0.0"
}
```
You'd need to provide a custom wrapper package for both of these, though, as I don't suppose that they come with any sort of `provide` clause out-of-the-box.

**Comment by franz-josef-kaiser** [comment]
Note to myself: Trac–Ticket–#33055 was merged in core, so `ext-curl` can go on the list.

**Comment by gmazzap** [comment]
Ok, to shorten this I referreed https://github.com/johnbillion/ext just trusting John Blackbourn.

I've added requirements to both v2 and v3. I guess this can be clsed.

Thanks anyone involved.
