### ISSUE TITLE
Additional configuration via extra settings

### ISSUE THREAD

**Issue by Giuseppe-Mazzapica** [wecodemore/wpstarter#3]
### Edited 16/03/15

- "gitignore" and  "env-example" also accept path of files, not only urls
- "gitignore.common" is `false` by default
- "env-example" is `false` by default
- "content-move" is renamed to "move-content" and set to `false` by default
- "force-gitignore" has been removed
- "prevent-overwrite" now allows fine-grained control using `$files` array
- "register-theme-folder" has been added

----

### Edited 08/03/15

- renamed "force-content-move" to "content-move"
- deleted "prevent-overwrite-hard" and added support for "hard" value in "prevent-overwrite"
- added support for "ask" value in "prevent-overwrite"

---

I have the idea to make possible to configure some aspects of the way WP Starter works thanks to `composer.json` extra settings.

I think all those configuration can be made available using a single `wpstarter` object as property of `extra` root object.

```json
{
    "extra" :
    {
       "wpstarter" : { }
    }
}
```

The configuration I plan to add are:

- **`"gitignore"`** with possible values:
    - `true`:    installation process doesn't ask any question and add default `.gitignore` file
    - `false`:  installation process doesn't ask nor add  `.gitignore` file
    - `"ask"`: installation process asks if to add  `.gitignore` file or not. Default behaviour.
    - `$url`: (string) should be the url or the path (relative to composer.json) of a `.gitignore` file. This file will be downloaded/copied and placed in project root folder
    - `$gitinore` (object) when used, no question is asked,  possible properties are:
        - `"common"`: (bool) common unrelevant files are added to `.gitignore` file when true. Default false
        - `"wp-content"`: (bool) `wp-content` folder is added to `.gitignore` file when true. Default true
        - `"vendor"`: (bool) vendor folder is added to `.gitignore` file when true. Default true
        - `"wp"`: (bool) WordPress package folder is added to `.gitignore` file when true. Default true
        - `"custom"`: (array) additional entries to add to `.gitignore` file . Default empty array

- **`"env-example"`**  with possible values:
  - `true`: installation process adds the default `.env.example` file
  - `false`: installation process doesn't add any `.env.example` file. Default behaviour.
  - `"ask"`:  installation process asks if add `.env.example` or not
  - `$url` (string): the url or the path (relative to composer.json) of a default `.env.example` file. This file will be downloaded and placed in project folder. This way is easy to have custom shared settings across projects

- **`"move-content"`** with possible values: 
  - `true`:   the `wp-content` folder contents are always moved from WP folder to project content folder, no question is asked during installation
  - `false`:  the `wp-content` folder contents aren't moved and no question is asked during installation.  Default behaviour.
  - `"ask"`: installation process asks if to move contents or not

- **`"register-theme-folder"`** with possible values: 
  - `true`:   the WordPress package `wp-content` folder is registered as additional theme folder (see #2 ) Default behaviour.
  - `false`:  the WordPress package `wp-content` folder is registered as additional theme folder.
  - `"ask"`: installation process asks if to register WP `wp-content` folder as additional theme folder.
 
 Note that `"register-theme-folder"` and `"move-content"` are incompatible settings. To allow wp-content folder movement `"move-content"` must be set to true and `"register-theme-folder"` to `false`.

- **`"prevent-overwrite"`** with possible values: 
  - `true`:  if any of target file exists it is not overwritten, a notice is printed to console.
  - `false`: installation process doesn't care if target files already exist, just overwrite them (actually this is not default behavior for `.gitignore` file so it will be overwritten if `"force-gitignore"` is true)
  - `"hard"`: if a `wp-config.php` file exists in project folder, installation process ends immedialy, just printing a notice
  - `"ask"`: if a file exists in target folder, installation process asks to overwrite it
 - `$files`: (array) array of files that should not be overwritten if found. is possible to use jolly characters to define files, e.g. `"*.php"`. The default settings is `[ ".gitignore" ]` it means .gitignore file by default is not overwritten if found. 

- **"`verbosity`"**  with possible values: 
  - 0:  no notice is printed by installation process. All questions just take default behavior if a specific setting is not set
  - 1: questions, warnings and errors are printed, all the rest (comments and informations) is skipped
  - 2:  current and default behavior, everything is printed to console

Opinions?

**Comment by franz-josef-kaiser** [comment]
> I think all those configuration can be made available using a single `wpstarter` object as property of the `extra` root object.

I agree 100%

> The configuration I plan to add are:

Not 100% convinced of the naming scheme yet. For e.g. `prevent-overwrite` - prevent to overwrite _what_ exactly? I'm in for a as-verbose-as-possible approach :) Also, this could be multi-dimensional and instead of having just yes/no/additional, be a container that allows to fine tune what to overwrite and what not by allowing file names as keys.

> `verbosity` with possible values: `0`, `1`, `2`

What I like about npm is that you can use `-v`, `-vv` an `-vvv` to adjust the verbosity-level. Not that I think that this is _the_ solution, but we could build upon it. I'm sure you remember [this WP.SE answer](http://wordpress.stackexchange.com/questions/119294/pass-boolean-value-in-shortcode/119299#119299). I'd just go with `filter_var( 'verbosity', FILTER_VALIDATE_BOOLEAN );` for the 1st and 2nd verbosity level to allow `0`, `false`, `off`, `no` `""` to turn things off (equals current `0`) and   `1`, `true`, `on`, `yes` to turn it on. For extra verbosity, we could use `medium` (3rd) and/or `max`/`maximum` for a possible 4th level.

> `"ask"`

My suggestion would be to use synonyms here as well. While `ask` is viable in a lot of spoken languages, programmers might use `prompt` as well. And if a program can help remembering the right settings by simply aliasing possible synonyms, it can help making less mistakes by mis-configuration.

> `"gitignore"` .. `$url`

While I think this is a great idea, I also think that this would make it possible to simply remove the defaults from the WPStarter stack. When there is an `array` allowed, we could point to [the GitHub/gitignore repo](https://github.com/github/gitignore/) in the docs and everybody could just cherry pick what s/he or the team needs. If the ignore files get appended to each other: Great move!

> `force-gitignore`

Imo this could be added to the `gitignore` settings, reducing the amount of top level keys.

One more thing: When we got a final draft of `extra` settings we maybe should review the wording again and try to standardize as much as possible. Maybe just throw this out on Twitter and G+ and ask for a vote or something like that.

**Comment by Giuseppe-Mazzapica** [comment]
> Not 100% convinced of the naming scheme yet. For e.g. prevent-overwrite - prevent to overwrite what exactly? I'm in for a as-verbose-as-possible approach :)

Ideally I would love to use WP Starter installation command as `post-update-cmd` script as well.
In that case a `prevent-overwrite` settings that in one line allow to prevent overwrite anything that already exists I think will be handy. But yes, I totally agree that a fine-grained control would be interesting as well, but more as an additional option than the unique choice.

---

> What I like about npm is that you can use -v, -vv an -vvv to adjust the verbosity-level. [...]

TBH I prefer numeric approach and just "force" users to use numerical values validated via

```php
$filtered = filter_var($verbosity, FILTER_VALIDATE_INT);
$verbosity = is_int($filtered) ? abs($filtered) : $default_verbosity; 
```
Reason is that a boolean validation doesn't make a lot of sense to me for a setting that is level-based.

Moreover, `filter_var($verbosity, FILTER_VALIDATE_BOOLEAN )` is *dangerous* because
`filter_var('unrelated-string-here-probably-for-mistake', FILTER_VALIDATE_BOOLEAN )` will be evaluated as `false` turning off verbosity (and so dangerously skipping questions...).

Moreover, looking at your example: `-v` / `-vv` / `-vvv`, what I said IMO make sense: a boolean validation in that case is not possible.

Moreover, by using a numerical approach we have possibility to add any additional level in future. Even better we can use `0` / `10` / `20` so that in feature we can easily add levels in the middle. After that in the code that have to use the setting, we can check using `>=` and `<=` instead of `=` that way users may set priority in settings using any number between `0` and `20` and not only that specific 3 numbers.

---

> "ask" ... My suggestion would be to use synonyms here as well.

Seems fine.

---

> .gitignore... While I think this is a great idea, I also think that this would make it possible to simply remove the defaults from the WPStarter stack. 

What I think it's nice in the default `.gitignore` in the repo is that is capable to ignore WP specific files / folders (WP path, `wp-config.php`) and `.env` file. Sure we can add that link to our docs, but I know for experience that a lot of users just don't read the docs. So to ignore sensible data per "default" IMO is better for users security. Of course, users that care can use config to do what they want.

Moreover, I'm formulating in my mind the idea to allow not only actual urls as `$url` setting for some files (`.gitignore`, `.env.example`), but also filesystem paths (relative to project root folder).

If we do that, people are able to create own Composer packages for those files, let Composer install them and then using `extra` setting to let WP Starter move files in right place.

Example:

```json
{
    "require" : {
          "wecodemore/wpstarter"        : "1.5",
          "gmazzap/my-wpstarter-files" : "*"
    },
    "extra" : {
         "wpstarter"                                : {
              "gitignore"        : "vendor/gmazzap/my-wpstarter-files/.gitignore",
              "env-example" : "vendor/gmazzap/my-wpstarter-files/.env.example"
         }
   }    
}
```

This way we let Composer download the files for us (and so we get support for private repositories and ssl *for free*) and at same time people are able to create their own WP Starter packages to share settings among projects as easy as heaven :)

---

> force-gitignore ... Imo this could be added to the gitignore settings, reducing the amount of top level keys.

Maybe we can just remove this setting and just use `prevent-overwrite` to prevent `.gitignore` overwrite. If we add fine-grained control for `prevent-overwrite` (as you suggested) that will be super easy and actually makes `force-gitignore` redundant.

---

> One more thing: When we got a final draft of extra settings we maybe should review the wording again and try to standardize as much as possible. Maybe just throw this out on Twitter and G+ and ask for a vote or something like that.

100% agree.

**Comment by Giuseppe-Mazzapica** [comment]
I edited OP, changes described there. Below there is entire wpstarter setting object using all current proposed settings with their default values:

```json
{
    "extra" : {
        "wpstarter" : {
            "gitignore" : "ask",
            "env-example" : false,
            "move-content" : false,
            "register-theme-folder" : true,
            "prevent-overwrite" : [
                ".gitignore"
            ],
            "verbosity": 2
        }
    }
}
```

**Comment by Giuseppe-Mazzapica** [comment]
Configuration has been implemented in [v.2.0](https://github.com/wecodemore/wpstarter/releases/tag/2.0.0)
