### ISSUE TITLE
Make WP Starter root path knowable

### ISSUE THREAD

**Issue by Giuseppe-Mazzapica** [wecodemore/wpstarter#30]
When installing a website with WP Starter, WordPress folder can be confured by using `wordpress-install-dir` configuration in `composer.json`.

In the default configuration (as provided by documentation) we set that folder to `public/wp`.

 That folder is then used to set `ABSPATH` WordPress constant in the loaded `wp-config.php`.

However, only relying on `ABSPATH` we have no clue about the "root" path of WP Starter (that is the path that contains the `.env` file).

Because it's true that with default configuration one can do `dirname(dirname(ABSPATH))`, but if the WordPress folder has been set to, for example,  `public/` that approach fails.

In my experience, is often useful to know to the root path of a website, because it is the place where one will commonly place different _things_ that need to go outside standard WordPress folder.

The path is already recognized during installation process, so it's easy to put in the generated `wp-config.php` _something_ that let us access the path from the rest of WordPress.

I think we have different options:

- define a constant: the most _WordPressy_ way, it's easy, but do we want yet another global constant?
- set an environment variable, works well but it a bit "fragile": environemt variables can esily be overwritten. Moreover there's no namespace for env vars, so they are global by definition...
- write a function that return the path. Functions return value can't be overwitten, and it is also possible to namespace a function... however to do it we should place 2 namespaces in `wp-config.php` that is doable, but not very clean. And if we use the root namespace we have a global function instead of a global contsant... not much better.

For these reasons I would go with the _WordPressy_ way, but open to hear different opinions.

**Comment by Giuseppe-Mazzapica** [comment]
I've added a PR with the new constant addition (#31), I'll wait some feedback before merging.

**Comment by dnaber-de** [comment]
Basically using a constant here is a reliable way. Just my two cents.

**Comment by Giuseppe-Mazzapica** [comment]
Done with f5084bf
