### ISSUE TITLE
Fix wrong variables in example env file

### ISSUE THREAD

**Issue by franz-josef-kaiser** [wecodemore/wpstarter#38]
In templates, the variables should look like in Bash: `${VARIABLE}` – see _PHP Dotenv_ and ["Nesting Variables"](https://github.com/vlucas/phpdotenv#nesting-variables). There's a typo with all of them: `{$VARIABLE}`. [Example](https://github.com/wecodemore/wpstarter/blob/23b3c870eab50973cf8d900f6aea95bf96a6c237/wpstarter/templates/.env.example#L80). That should get fixed.

**Comment by franz-josef-kaiser** [comment]
See PR #39

**Comment by Giuseppe-Mazzapica** [comment]
Done with 759782a
