### ISSUE TITLE
phpcs.xml

### ISSUE THREAD

**Issue by GaryJones** [wecodemore/wpstarter#47]
A recent commit adjusted a whole load of code, for the purposes of code standards, but there is no suggestion as to what the code standard to be followed is.

I'd suggest a `phpcs.xml` file in the root of the project, that allows for programatic testing (i.e, pre-commit hooks) of the standards, and an agreement on which standards should be used.

**Comment by franz-josef-kaiser** [comment]
There are some free services that we could use. It would be nice to rely on a service instead of a Git hook as the hook might not be available on all branches all time.

* [Coveralls](https://coveralls.io/)
* [Code Climate](https://codeclimate.com/)
* …?

**Comment by GaryJones** [comment]
Even something like Travis CI can be made to do the same check.

I think @schlessera has a pre-commit hook package for doing CS checks like these.

The advantage of pre-commit hook, is that it's local - you don't have to push a branch to GitHub, and wait for a CI service to run, before seeing that you've missed some whitespace, and then having to do new commits and rebase the PR etc.

**Comment by franz-josef-kaiser** [comment]
@GaryJones  You might want to look through open and closed issues on [_grunt-githooks_](https://github.com/wecodemore/grunt-githooks) for some of the pros/cons and things to be aware of with Git hooks.

**Comment by gmazzap** [comment]
phpcs.xml.dist is in the repo. This can be closed. Thanks!
