### ISSUE TITLE
Defining WP_CONTENT_URL is problematic on multisite with different domains

### ISSUE THREAD

**Issue by dnaber-de** [wecodemore/wpstarter#48]
WPStarter defines the constant `WP_CONTENT_URL` in generated `wp-config.php`:

```
/**
 * Define content constants only if needed, or network install screen will complain for no reason
 */
if (realpath(dirname(__DIR__).'/public/wp-content') !== realpath(ABSPATH.'/wp-content')) {
    defined('WP_CONTENT_DIR') or define('WP_CONTENT_DIR', realpath(dirname(__DIR__).'/public/wp-content'));
    defined('WP_CONTENT_URL') or define('WP_CONTENT_URL', rtrim(WP_HOME, '/').'/wp-content');
}
```

My configuration is:

```
"extra": {
    "wordpress-install-dir": "public/wp",
    "wordpress-content-dir": "public/wp-content",
    "installer-paths": {
        "public/wp-content/plugins/{$name}/": [ "type:wordpress-plugin" ],
        "public/wp-content/themes/{$name}/": [ "type:wordpress-theme" ]
    },
    "wpstarter": {
        "register-theme-folder": false,
        "prevent-overwrite": [ ".gitignore" ]
    }
}
```

In case of multisite with different domains, this leads to issues with cross-origin policy. E.g. `WP_HOME` is set to `http://site-a.tld`. On site `site-b.tld` assets will get enqueued with the domain of site A. In my specific case the browser does not request font files that are referenced with a relative path from a style sheet. However It could be hot-fixed by adding a Access-Control header but that wouldn't solve the actual problem that `WP_CONTENT_URL` does not match the `home_url()`.

From the code comment, this is only needed for the network install screen, so maybe we should define these constants only if `MULTISTIE` is not defined or `false`?

I'll test the suggested fix and provide a PR if appreciated.

**Comment by dnaber-de** [comment]
Update: didn't forget that, just didn't found time yet. I guess I find some the next days.

**Comment by dnaber-de** [comment]
Anything needs to be done or tested here?

**Comment by gmazzap** [comment]
@dnaber-de I did not have chance to test this. What happen in multisite when content folder is ouside WordPress folder and WP_CONTENT_URL is not defined? Is WordPress able to resolve URLs correctly on its own or something else needs to be done to make it work?

**Comment by gmazzap** [comment]
The comment on the code tells that we define the coinstants only when needed, that is when content folder is outside WordPress folder.

When content folder is equal to `ABSPATH . '/wp-content'` (default WP location) we don't need to declare any constant, because WordPress will be able to solve it properly. 

But in case ` '/wp-content'` is outside WP folder, I don't know if WordPress can work properly without defining `WP_CONTENT_DIR` and `WP_CONTENT_URL`.

I think that at list the path have to be defined...

**Comment by dnaber-de** [comment]
Sure `WP_CONTENT_DIR` has to be defined, but the patch doesn't affect this part. It still gets defined.

Look at my configuration above: 
```
"extra": {
    "wordpress-install-dir": "public/wp",
    "wordpress-content-dir": "public/wp-content",
}
```
`wp-content` folder is outsite of `wp` folder. The current code assumes that the `public/` part of the path is the Document Root (Web Root):

```
defined('WP_CONTENT_URL') or define('WP_CONTENT_URL', rtrim(WP_HOME, '/').'/wp-content');
```

This is pretty much the same what WordPress does in `default-constants.php`:
```
if ( !defined('WP_CONTENT_URL') )
		define( 'WP_CONTENT_URL', get_option('siteurl') . '/wp-content'); // full url - WP_CONTENT_DIR is defined further up
```
With the one small difference that WordPress has already »sunrised« the current site. 

So the patch doesn't change anything on the default behavior but allowing Multisite with different domains.

**Comment by gmazzap** [comment]
Yes @dnaber-de I misread you PR. It seemed to me that the condition affected both constants (`WP_CONTENT_DIR` and `WP_CONTENT_URL`) but it only affects the latter.

I'll merge.

**Comment by gmazzap** [comment]
Done in 508e48d
