### ISSUE TITLE
RuntimeException because DB_NAME, DB_USER, DB_PASSWORD not set

### ISSUE THREAD

**Issue by gmazzap** [wecodemore/wpstarter#49]
_Sometimes_ this error appear when using WP Starter:

> Fatal error: Uncaught RuntimeException: DB_NAME, DB_USER, DB_PASSWORD environment variables are required.

As of now, this bug has been reproduced in Windows + Apache systems.

It has been reported by different users, however the bug is always very inconsistent: it just appear on "some" requests, even if **nothing** changed between not working and working requests.

@danielhuesken reported that the problem disappeared if `immutable` option in `Loader` was set to `true` and that the offending line is https://github.com/wecodemore/wpstarter/blob/master/wpstarter/src/Env/Loader.php#L34-L36.

If that is confirmed, means that the bug can be tracked down to `$this->getEnvironmentVariable($name)` (where `$this` is an instance of [`Dotenv\Loader`](https://github.com/vlucas/phpdotenv/blob/master/src/Loader.php)) returning something not `null`, at the start of the request, but only "sometimes" and only in Windows + Apache systems.

I can confirm that restarting Apache immediately and always make bug disappear (when it is there).

**Comment by tfrommen** [comment]
Fixed in 315a197c7fffdcf2458298b552c0cf805c220481.
