### ISSUE TITLE
WP CLI couldn't read DB table prefix

### ISSUE THREAD

**Issue by GaryJones** [wecodemore/wpstarter#61]
For a new site, I cloned the client's Bitbucket repo that had the initial files for WPStarter, and got the site up and running. All fine.

When I tried WP CLI though, I kept coming across errors like this:

![wp-cli](https://cloud.githubusercontent.com/assets/88371/23146100/bd87b73e-f7cb-11e6-81d4-e6f3fa982866.png)

@schlessera's conclusion was that the DB prefix was not recognised when WP-CLI parsed the config. My `.env` (edited with nano on the server, but I can't spot any line-ending issues when opening on my Mac) contained:

```
DB_TABLE_PREFIX=wpcwr_
```

Changing it to:
```
DB_TABLE_PREFIX=wpcwr_
```

didn't help.

Alain's solution was to hard code the prefix in `wp-config.php`:

<img width="450" alt="screenshot 2017-02-21 01 15 50" src="https://cloud.githubusercontent.com/assets/88371/23146177/64825ea4-f7cc-11e6-8de5-7ff318cf0aa1.png">

And this worked - WP CLI could run as per normal with no errors.

So, why couldn't the`.env` table prefix be recognised before it got to this part of `wp-config.php`?

**Comment by gmazzap** [comment]
Merged and released in v2.4.2 https://github.com/wecodemore/wpstarter/releases/tag/2.4.2
