### ISSUE TITLE
relative path in wp-cli.yml

### ISSUE THREAD

**Issue by danielhuesken** [wecodemore/wpstarter#65]
Can you make the path in wp-cli.yml relative. The problem is that i can access the project under linux and windows and they have different path. With a relative path i can use wp-cli on both without adding the --dir paramter.
Example: `path: ./public/wp`

**Comment by gmazzap** [comment]
@danielhuesken Just pushed to `dev` branch. Can you please test it?

**Comment by danielhuesken** [comment]
@gmazzap it seems to be work ;)

**Comment by gmazzap** [comment]
Merged and released in v2.4.2 https://github.com/wecodemore/wpstarter/releases/tag/2.4.2
