### ISSUE TITLE
.gitignore possible to place it in another path, via extra settings?

### ISSUE THREAD

**Issue by elvismdev** [wecodemore/wpstarter#66]
Wonder if this is possible somehow at this moment? We'd like to place the `.gitignore` created by WP Starter, in another subfolder instead of the root level from where composer is run, e.g. inside `<root>/public/`

Is this something currently achievable trough extra settings in the composer.json file?

In case is not, could be implemented for a future WP Starter release? Thinking about:

```
{
    "extra" : {
        "wpstarter" : {
            "gitignore-path" : "./public",
            "prevent-overwrite" : [
                ".gitignore"
            ],
        }
    }
} 
```

**Comment by gmazzap** [comment]
Hi @elvismdev and thanks for your interest.

At the moment that's not possible. But more flexibility on file creation is already planned in version 3 which is in the works, but no ETA.

**Comment by lkraav** [comment]
> Wonder if this is possible somehow at this moment? We'd like to place the .gitignore created by WP Starter, in another subfolder instead of the root level from where composer is run, e.g. inside <root>/public/

@elvismdev what's the use case for this?

**Comment by gmazzap** [comment]
For v2 this is not gonna change.

For v3 I've reconsidered the creation of a gitignore step at all, my experience in 3 years usage of WP Starter has been that manually created .gitignore has worked best.

With custom steps in v3 people can create one if they want. So this issue make no much sense to be opened.

Thanks anyone involved.
