### ISSUE TITLE
Default WP_HOME causes fatal error

### ISSUE THREAD

**Issue by Chrico** [wecodemore/wpstarter#76]
**Describe the bug**
If i don't have a WP_HOME defined in my `.env`-file, WPStarter is falling back to a generated one. This generation uses `set_url_scheme` which is not available at the point it is called. I can see following fatal thrown:

```
Fatal error: Uncaught Error: Call to undefined function set_url_scheme() in E:\Projects\xyz/customer-website\public\wp-config.php:121
```

----

**To Reproduce**
1. Create an `.env` file with following without `WP_HOME`.
2. run `composer wpstarter` to generate `wp-config.php
3.  Open project in Browser.

----

**Expected behavior**
v1: Function should be included or a custom implementation.

v2:  WPStarter should not set "defaults" by assuming something in `wp-config.php` - it should show an error on CLI when "required" constants are not set.

**Comment by gmazzap** [comment]
Thanks, I will fix the issue.

Regarding _Expected behavior_ v2, WP_HOME is not strictly required. Surely is recommended. I could document that (it is already documented in the .env.example).

The fallback to server name or localhost can work in many cases... for the others, the env var is there. Don't want to throw a fatal for tis reason

**Comment by gmazzap** [comment]
@Chrico the issue should be fixed. Special behavior of WP_HOME is also documented now: https://github.com/wecodemore/wpstarter/blob/version-3/docs/03-WordPress-Integration.md#wp_home

**Comment by Chrico** [comment]
Thanks! Looks fine to me.

Commit: https://github.com/wecodemore/wpstarter/commit/c94123d3b4af10f12bf22a661d3c1aba1d63d52a
