### ISSUE TITLE
Consider using WPCS for `index.php` and `wp-config.php` files

### ISSUE THREAD

**Issue by schlessera** [wecodemore/wpstarter#84]
The files `public/index.php` and `public/wp-config.php` are perceived as being part of the WordPress installation. Also, the `public/wp-config.php` more specifically is something that WordPress developers will be peeking into.

It might make more sense to switch these two files from PSR-2 to WPCS, to have the experience be less jarring for the standard WordPress developer.

**Comment by gmazzap** [comment]
Considering this, the two files are not present in the repo, I have _templates_ for them. And templates are part of this project so I think they should use the same PHPCS of the project.

Leaveng this opened a bit to give the possibility to reply, will close later if stale.

**Comment by gmazzap** [comment]
Decided to close this.

`wp-config.php` is pretty complex in v3, and I don't want to have a lot of code part of WP Starter to use a different CS.

Besides that, WP Starter `wp-config.php` is right now *very* different from WP version of it.
So a "standard" WP developer would get "surprised" anyway.
