### ISSUE TITLE
Add notice/link in `02-Environment-Variables` about env cache

### ISSUE THREAD

**Issue by schlessera** [wecodemore/wpstarter#85]
The environment cache is described in `03-WordPress-Integration`.

However, if someone has trouble with getting their changes to the `.env` be recognized and are unaware of the caching, they will probably look in `02-Environment-Variables` to solve this issue.

There should be either a notice or a link to that effect in `02-Environment-Variables` to make sure people quickly find out what the problem is.

**Comment by gmazzap** [comment]
I actually moved the detailed documntation in [02-Environment-Variables.md](https://github.com/wecodemore/wpstarter/blob/dev/docs/02-Environment-Variables.md#cached-environment) file and added a note in the [03-WordPress-Integration.md](https://github.com/wecodemore/wpstarter/blob/dev/docs/03-WordPress-Integration.md#cached-environment) file.

Thanks for the suggestion. Closing.
