### ISSUE TITLE
`wpstarter` binary should be able to show a list of recognized steps

### ISSUE THREAD

**Issue by schlessera** [wecodemore/wpstarter#86]
Although you can run individual steps through the `wpstarter` binary, it cannot provide a list of recognized steps. Discovering the available steps requires going through the code of all the individual steps to find the names.

It would be useful to have a more convenient discovery mechanism for this, either by having `wpstarter --help` immediately show the list of recognized steps, or by having a separate subcommand to list these steps.

**Comment by gmazzap** [comment]
d1033d0 Introduce **`composer wpstarter --steps-help`**.

It lists dyanamically all steps, including the custom, and excluding those disabled.
Tests and documentationa re also there.
