### ISSUE TITLE
How does WPStarter compare to WordPlate and Bedrock

### ISSUE THREAD

**Issue by ibes** [wecodemore/wpstarter#87]
Hi there,

I am happy that it is getting more and more common to use Composer in WordPress land. 
I just resently stumbled over WP Starter and would like to ask how WP Starter is different from

Bedrock: https://github.com/roots/bedrock
and
WordPlate: https://github.com/wordplate/wordplate

I see all three projects use composer to require the WP package of John P. Bloch. 
All three projects make use of .env environments
All three projects have found a solution to make MU plugins requirable. 

So far I just used WordPlate and am very happy to have Composer in my workflow that way. 

Bedrock seems to try to solve quite a lot and felt complicated to me (even if it maybe is not). 
WordPlate seemed as easy as it can to me - but actually it also needs quite a bit of learning and it makes it's love to Laravel clear by bringing mix and other Laravel components in the project. 

I see a couple of things in WP Starter that I have not seen in the other projects and I am wondering if you managed to solve things more elegant than the other projects. 

This or that way I am happy that there are options :)

**Comment by lkraav** [comment]
I asked the same question about Bedrock just recently https://discourse.roots.io/t/research-bedrock-vs-wp-starter-by-gmazzap/14044 and @gmazzap was kind enough to answer with details.

WordPlate I didn't even know about, thanks.

**Comment by gmazzap** [comment]
Hi @ibes 

thanks for your interest.

> I see all three projects use composer to require the WP package of John P. Bloch.

Not really. Bedrock switched to [own package](https://packagist.org/packages/roots/wordpress).

WP Starter 2 used to require WP package of John P. Bloch, in [v3]https://github.com/wecodemore/wpstarter/releases/tag/3.0.0-beta.1), now in beta, it does not require any specific WP package, but you can require what you prefer.

> All three projects make use of .env environments

WP Starter 3 makes use of symfony/dotenv and do not require .env file, but environment variables can be in actual environment, e.g. in platform settings or web server configuration

In all honesty I don't know much about WordPlate. In the regard of Bedrock this question has been asked other times, you can find an answer here: https://discourse.roots.io/t/research-bedrock-vs-wp-starter-by-gmazzap/14044/4

> All three projects have found a solution to make MU plugins requirable.

WP Starter 3 make MU plugins requirable, but do not offer any special feature to use regular plugins as MU plugins (Bedrock has that).

---

If you want to learn more about WP Starter 3, that is quite different than its v2 version, you can start reading its docs here: https://github.com/wecodemore/wpstarter/blob/dev/docs/01-Introduction.md

---

That said, in all honesty, I don't know much about WordPlate. In the regard of Bedrock this question has been asked other times, and has an answer here https://discourse.roots.io/t/research-bedrock-vs-wp-starter-by-gmazzap/14044/4 (an I might be wrong, but at first glance it seems that differences mentioned there for Bedrock apply to WordPlate as well).

Moreover, WordPlate looks a complete framework that take care of the entire application building (so it looks like an alternative to Bedrock + Sage) WP Starter does nothing like that, and leave people free to use whatever they like to build their applications.

**Comment by ibes** [comment]
Thanks @gmazzap for the fast and great reply. 

Sounds like WP Starter is really an own idea for itself.

I feel like Bedrock and WordPlate are quite similar but different flavors. 
WP Starter really seems to be a category for itself.

Super curious to follow the development of WP Starter 3.
Will watch the repo :)

**Comment by gmazzap** [comment]
Closing. Maybe we'll document this thing at some point.
