### ISSUE TITLE
New pull request for documentation on dev branch

### ISSUE THREAD

**Issue by wunluv** [wecodemore/wpstarter#96]
I've created a new pull request here: https://github.com/wecodemore/wpstarter/pull/95 and I'll be creating more as I go through the documentation. I wanted to check in before continuing to confirm that I'm doing this correctly. This is my first pull request on Github ;)

Thanks.

**Comment by gmazzap** [comment]
Thank you very much @wunluv 

You've done very well :)  When a PR needs code change in your interest it is better to open an issue _before_ , to avoid doing work that will not be merged.

For documentation changes, that is likely not necessary, especially when you fix my broken English :)

I gave feedback on your PR and if you could address that I will be very happy to merge.

Thanks a lot!
