### ISSUE TITLE
How to place github package in plugins directory?

### ISSUE THREAD

**Issue by pawelkmpt** [wecodemore/wpstarter#99]
I have custom github packages added to `composer.json`, they're installed in `vendor` directory and not available in `plugins` directory.

I tried to add packages names in `installer-paths` extra setting but it didn't help. Probably because these packages don't have `type` specified in `composer.json` and don't use `composer/installers` like mentioned in [docs](https://github.com/composer/installers#custom-install-paths): 

> If you are consuming a package that uses the `composer/installers` you can override the install path

What would be the correct approach to copy (or immediately install) such packages in `plugins` directory? Is it possible out of the box but I'm not seeing it in docs or should be custom implemented?

**Comment by pawelkmpt** [comment]
I found a solution thanks to @saas786. You have to set `"type": "wordpress-plugin"` in package definitions, eg.:

```json
{
    "type": "package",
    "package": {
        "name": "Automattic/sensei",
        "version": "2.1.2",
        "type": "wordpress-plugin",
        "source": {
            "url": "https://github.com/Automattic/sensei.git",
            "type": "git",
            "reference": "origin/master"
        }
    }
}
```

**Comment by lkraav** [comment]
@pawelkmpt do you think this is a missing piece of documentation?

**Comment by pawelkmpt** [comment]
@lkraav it would've saved me some time if it was in docs

**Comment by gmazzap** [comment]
@pawelkmpt I understand, but this is not an issue with WP Starter. Maybe you could send a PR and improving docs on `composer/installers`.
